name: Update Docker Hub README

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'README.md'
  workflow_dispatch:

env:
  DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/snapdocs

jobs:
  update-readme:
    name: Update Docker Hub README
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_IMAGE }}
          readme-filepath: ./README.md
          short-description: 'SnapDocs - Open source, self-hostable document workspace with real-time collaboration'